export interface ThemePreset {
  id: string;
  name: string;
  badge: string;
  description: string;
  color: string;
  bubble: string;
  text: string;
  main_bg: string;
  card_bg: string;
  border_color: string;
  incoming_bubble: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "obsidian-noir",
    name: "Obsidian Noir",
    badge: "Siyaha Yakın Derin Koyu",
    description: "Discord, Linear ve macOS ilhamlı; göz yormayan derin obsidian, antrasit kömür ve çinko zemin.",
    color: "#818CF8",
    bubble: "#27272A",
    text: "#F4F4F5",
    main_bg: "#09090B",
    card_bg: "#121215",
    border_color: "#27272A",
    incoming_bubble: "#18181B",
  },
  {
    id: "linear-obsidian",
    name: "Linear Midnight",
    badge: "Varsayılan SaaS",
    description: "Linear & Vercel ilhamlı; göz yormayan derin çivit ve gece mavisi.",
    color: "#6366F1",
    bubble: "#4F46E5",
    text: "#FFFFFF",
    main_bg: "#090A0F",
    card_bg: "#11141E",
    border_color: "#1E2333",
    incoming_bubble: "#181C28",
  },
  {
    id: "supabase-emerald",
    name: "Supabase Emerald",
    badge: "Siber Zümrüt",
    description: "Supabase tarzı fütüristik zümrüt yeşili ve mat antrasit zemin.",
    color: "#10B981",
    bubble: "#059669",
    text: "#FFFFFF",
    main_bg: "#080E0B",
    card_bg: "#0E1713",
    border_color: "#192B23",
    incoming_bubble: "#14221C",
  },
  {
    id: "raycast-midnight",
    name: "Raycast Midnight",
    badge: "Kozmik Mor",
    description: "Raycast Theme Studio esintili, asil ve derin elektrik moru tonları.",
    color: "#A855F7",
    bubble: "#7E22CE",
    text: "#FFFFFF",
    main_bg: "#0C0A14",
    card_bg: "#141021",
    border_color: "#241C38",
    incoming_bubble: "#1C162E",
  },
  {
    id: "telegram-amoled",
    name: "Telegram AMOLED",
    badge: "Zifiri Siyah",
    description: "OLED ekranlar için pil tasarruflu gerçek %100 siyah (#000000).",
    color: "#229ED9",
    bubble: "#1E4E79",
    text: "#FFFFFF",
    main_bg: "#000000",
    card_bg: "#0D0D0D",
    border_color: "#222222",
    incoming_bubble: "#181818",
  },
  {
    id: "whatsapp-stealth",
    name: "WhatsApp Stealth",
    badge: "Klasik Koyu",
    description: "Koyu petrol mavisi-yeşili ve kurşun zemin uyumu.",
    color: "#25D366",
    bubble: "#005C4B",
    text: "#E9EDEF",
    main_bg: "#0C1317",
    card_bg: "#111B21",
    border_color: "#222D34",
    incoming_bubble: "#202C33",
  },
  {
    id: "nordic-arctic",
    name: "Nordic Arctic",
    badge: "Soğuk Grafit",
    description: "macOS ve GitHub Dark soğuk grafit ve gök mavisi.",
    color: "#38BDF8",
    bubble: "#0284C7",
    text: "#FFFFFF",
    main_bg: "#0B111A",
    card_bg: "#111923",
    border_color: "#1E2D3D",
    incoming_bubble: "#192535",
  },
  {
    id: "cyber-crimson",
    name: "Cyber Crimson",
    badge: "Aura Rose",
    description: "Modern neon gül ve yakut kadife tonlarıyla lüks bir hava.",
    color: "#F43F5E",
    bubble: "#BE123C",
    text: "#FFFFFF",
    main_bg: "#0D080A",
    card_bg: "#160F13",
    border_color: "#2B1922",
    incoming_bubble: "#1F141A",
  },
  {
    id: "warm-amber",
    name: "Warm Amber",
    badge: "Sıcak Kehribar",
    description: "Espresso, kavrulmuş fındık ve yumuşak altın tonları.",
    color: "#F59E0B",
    bubble: "#B45309",
    text: "#FFFFFF",
    main_bg: "#0E0C0A",
    card_bg: "#161310",
    border_color: "#2B231C",
    incoming_bubble: "#211C17",
  },
  {
    id: "titanium-mono",
    name: "Titanium Mono",
    badge: "Minimalist Mat",
    description: "Ultra sade, dikkat dağıtmayan titanyum mat koyu gri.",
    color: "#94A3B8",
    bubble: "#334155",
    text: "#F8FAFC",
    main_bg: "#0B0C0E",
    card_bg: "#131519",
    border_color: "#23272F",
    incoming_bubble: "#1C1F26",
  },
];
